<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IEVL217" ignored="0" tests="2" failures="1" timestamp="2019-09-18T18:37:40 EEST" time="8.117" errors="0">
  <testcase name="mobileDriver" time="7.817" classname="allure"/>
  <testcase name="testForSum" time="0.03" classname="allure">
    <failure type="java.lang.AssertionError" message="Ð¡ÑƒÐ¼Ð¼Ð° Ñ�Ð»Ð°Ð³Ð°ÐµÐ¼Ñ‹Ñ… Ð½Ðµ Ñ�Ð¾Ð¾Ñ‚Ð²ÐµÑ‚Ñ�Ñ‚Ð²ÑƒÐµÑ‚ Ð¾Ð¶Ð¸Ð´Ð°ÐµÐ¼Ð¾Ð¼Ñƒ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸ÑŽ did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Ð¡ÑƒÐ¼Ð¼Ð° Ñ�Ð»Ð°Ð³Ð°ÐµÐ¼Ñ‹Ñ… Ð½Ðµ Ñ�Ð¾Ð¾Ñ‚Ð²ÐµÑ‚Ñ�Ñ‚Ð²ÑƒÐµÑ‚ Ð¾Ð¶Ð¸Ð´Ð°ÐµÐ¼Ð¾Ð¼Ñƒ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸ÑŽ did not expect to find [true] but found [false]
at allure.checkSumStep(allure.java:22)
at allure.testForSum(allure.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testForSum -->
</testsuite>
